ARG BUILDPLATFORM=linux/amd64
ARG VARNISH_VERSION_NUMBER=9.0.3-1
FROM --platform=$BUILDPLATFORM golang:1.26-bookworm AS builder

ENV DEBIAN_FRONTEND=noninteractive INSTALL_DIRECTORY=/usr/local/bin

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends git curl

WORKDIR /go/src/github.com/cin/varnish-operator

ENV GOPROXY=https://proxy.golang.org

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY pkg ./pkg
COPY api/ api/

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG VERSION=undefined

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build \
    -ldflags "-X main.Version=$VERSION" \
    -a \
    -o varnish-controller \
    ./cmd/varnish-controller/


FROM --platform=$BUILDPLATFORM debian:trixie-slim
LABEL maintainer="Alex Lytvynenko <oleksandr.lytvynenko@ibm.com>, Tomash Sidei <tomash.sidei@ibm.com>"

COPY docker/install-varnish-9.sh /tmp/install-varnish-9.sh
RUN chmod +x /tmp/install-varnish-9.sh \
    && VARNISH_VERSION_NUMBER="${VARNISH_VERSION_NUMBER}" /tmp/install-varnish-9.sh tools \
    && rm /tmp/install-varnish-9.sh

COPY --from=builder /go/src/github.com/cin/varnish-operator/varnish-controller /varnish-controller
RUN chown varnish:varnish /varnish-controller /usr/bin/varnishadm /usr/bin/varnishstat

USER varnish

ENTRYPOINT ["/varnish-controller"]
